# Generated from the vendor synth_1 run script (Vivado 2024.1, Jul 2025).
# Paths are relative to the repo root. Order preserved from the vendor run.
set VERILOG_SOURCES {
  fpga/lib/dsp/acc.v
  fpga/lib/dsp/add2.v
  fpga/lib/dsp/add2_and_clip.v
  fpga/lib/dsp/add2_and_clip_reg.v
  fpga/lib/dsp/add2_and_round.v
  fpga/lib/dsp/add2_and_round_reg.v
  fpga/lib/dsp/add2_reg.v
  fpga/lib/dsp/add_then_mac.v
  fpga/lib/fifo/axi_demux4.v
  fpga/lib/fifo/axi_fifo.v
  fpga/lib/fifo/axi_fifo32_to_fifo64.v
  fpga/lib/fifo/axi_fifo64_to_fifo32.v
  fpga/lib/fifo/axi_fifo_2clk_xpm.v
  fpga/lib/fifo/axi_fifo_bram.v
  fpga/lib/fifo/axi_fifo_flop.v
  fpga/lib/fifo/axi_fifo_flop2.v
  fpga/lib/fifo_200/axi_fifo_legacy.v
  fpga/lib/fifo/axi_fifo_short.v
  fpga/lib/fifo/axi_mux4.v
  fpga/lib/fifo/axi_packet_gate.v
  fpga/top/b200/b200_core.v
  fpga/top/b200/b200_io.v
  fpga/lib/control/bin2gray.v
  fpga/lib/control/binary_encoder.v
  fpga/lib/vita_200/chdr_12sc_to_16sc.v
  fpga/lib/vita_200/chdr_16sc_to_12sc.v
  fpga/lib/vita_200/chdr_16sc_to_32f.v
  fpga/lib/vita_200/chdr_16sc_to_8sc.v
  fpga/lib/vita_200/chdr_16sc_to_xxxx_chain.v
  fpga/lib/vita_200/chdr_32f_to_16sc.v
  fpga/lib/vita_200/chdr_8sc_to_16sc.v
  fpga/lib/vita_200/chdr_xxxx_to_16sc_chain.v
  fpga/lib/dsp/cic_dec_shifter.v
  fpga/lib/dsp/cic_decim.v
  fpga/lib/dsp/cic_int_shifter.v
  fpga/lib/dsp/cic_interp.v
  fpga/lib/dsp/cic_strober.v
  fpga/lib/dsp/clip.v
  fpga/lib/dsp/clip_reg.v
  fpga/lib/vita_200/context_packet_gen.v
  fpga/lib/dsp/cordic_stage.v
  fpga/lib/dsp/cordic_z24.v
  fpga/lib/control_200/cvita_uart.v
  fpga/lib/dsp/ddc_chain.v
  fpga/lib/dsp/duc_chain.v
  fpga/lib/gpif2/fifo64_to_gpif2.v
  fpga/lib/vita_200/float_to_iq.v
  fpga/lib/gpif2/gpif2_error_checker.v
  fpga/lib/gpif2/gpif2_slave_fifo32.v
  fpga/lib/gpif2/gpif2_to_fifo64.v
  fpga/lib/control/gpio_atr.v
  fpga/lib/control/gpio_atr_io.v
  fpga/lib/control/gray2bin.v
  fpga/lib/dsp/hb47_int.v
  fpga/lib/dsp/hb_dec.v
  fpga/lib/dsp/hb_interp.v
  fpga/top/b200/coregen_dsp/hbdec1.v
  fpga/top/b200/coregen_dsp/hbdec2.v
  fpga/lib/vita_200/iq_to_float.v
  fpga/lib/vita_200/new_rx_control.v
  fpga/lib/vita_200/new_rx_framer.v
  fpga/lib/vita_200/new_tx_control.v
  fpga/lib/vita_200/new_tx_deframer.v
  fpga/lib/timing/pps_generator.v
  fpga/lib/control_200/radio_ctrl_proc.v
  fpga/lib/radio_200/radio_legacy.v
  fpga/lib/control/ram_2port.v
  fpga/lib/control/reset_sync.v
  fpga/lib/dsp/round.v
  fpga/lib/dsp/round_reg.v
  fpga/lib/dsp/round_sd.v
  fpga/lib/control/serial_to_settings.v
  fpga/lib/control/setting_reg.v
  fpga/lib/dsp/sign_extend.v
  fpga/lib/control/simple_spi_core.v
  fpga/lib/wishbone/simple_uart.v
  fpga/lib/wishbone/simple_uart_rx.v
  fpga/lib/wishbone/simple_uart_tx.v
  fpga/lib/dsp/small_hb_dec.v
  fpga/lib/dsp/small_hb_int.v
  fpga/lib/packet_proc_200/source_flow_control_legacy.v
  fpga/lib/dsp/srl.v
  fpga/lib/control/synchronizer.v
  fpga/lib/control/synchronizer_impl.v
  fpga/lib/timing/time_compare.v
  fpga/lib/timing/timekeeper_legacy.v
  fpga/lib/vita_200/trigger_context_pkt.v
  fpga/lib/vita_200/tx_responder.v
  fpga/lib/control/user_settings.v
  fpga/top/b200/gnss_pps_telemetry.v
  fpga/top/b200/gps_uart_bridge.v
  fpga/top/b200/gps_autoconfig.v
  fpga/top/b200/adf4001_guard.v
  fpga/top/b200/adc_monitor.v
  fpga/top/b200/osc_monitor.v
  fpga/lib/dsp/rnd_clip_slice.v
  fpga/lib/dsp/droop_comp.v
  fpga/lib/dsp/wb_fir.v
  fpga/top/b200/b200.v
}
