#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Wideband (decimation 1) filter profiles for the B200 DDC (N6).

At decimation 1 the FPGA does no filtering: the band edges are whatever the
AD9361's own filters leave, and at 56-61.44 MS/s that is nearly nothing (the
noise floor is flat to fs/2, so anything folding in from beyond Nyquist lands
in the outer part of the band). wb_fir.v is a 33-tap symmetric FIR at the
output rate, active only at decimation 1, with a few selectable profiles.
Profile 0 is a true bypass (no delay). Coefficients are 18-bit, DC gain 2^16.

    python3 wb_fir.py study          # achieved ripple / attenuation per profile
    python3 wb_fir.py vh OUT         # coefficient include for the HDL
    python3 wb_fir.py vectors OUT    # test vectors for fpga/sim/wb_fir_tb.v
"""
import sys
import numpy as np
from scipy import signal

NT = 33                # taps (symmetric: 17 distinct coefficients)
COEF_BITS = 18
COEF_FRAC = 16

# profile: (passband edge, stopband edge, stopband weight), fractions of fs.
PROFILES = {
    1: (0.42, 0.49, 3.0),    # clean band edges: the plan's N6 target
    2: (0.40, 0.47, 2.0),    # wider guard band
    3: (0.36, 0.44, 8.0),    # strongest rejection, narrower passband
}


def design(fp, fst, w):
    h = signal.remez(NT, [0, fp, fst, 0.5], [1, 0], weight=[1, w], fs=1.0, maxiter=400)
    return h / h.sum()


def quantize(h):
    """Round to COEF_FRAC bits, symmetric, DC gain exactly 2^COEF_FRAC."""
    q = np.round(h * (1 << COEF_FRAC)).astype(np.int64)
    q = (q + q[::-1]) // 2 if not np.array_equal(q, q[::-1]) else q
    q[NT // 2] += (1 << COEF_FRAC) - q.sum()
    assert np.all(np.abs(q) < (1 << (COEF_BITS - 1)))
    return q


def coefs(profile):
    """The 17 distinct coefficients c0..c16 (c16 = centre) of a profile."""
    if profile == 0:
        return [0] * (NT // 2) + [1 << COEF_FRAC]
    q = quantize(design(*PROFILES[profile]))
    return [int(v) for v in q[:NT // 2 + 1]]


def response(c, f):
    taps = np.array(list(c) + list(c[-2::-1]), float) / (1 << COEF_FRAC)
    _, H = signal.freqz(taps, worN=f, fs=1.0)
    return 20 * np.log10(np.abs(H) + 1e-15)


def check(profile):
    fp, fst, _ = PROFILES[profile]
    f = np.linspace(0, 0.5, 8001)
    m = response(coefs(profile), f)
    pb, sb = m[f <= fp], m[f >= fst]
    return pb.max() - pb.min(), -sb.max(), m[np.argmin(np.abs(f - 0.49))]


def study():
    for p in PROFILES:
        r, a, a49 = check(p)
        fp, fst, _ = PROFILES[p]
        print(f"profile {p}: pass 0..{fp} fs ripple {r:.3f} dB p-p, stop {fst}..0.5 fs >= {a:.1f} dB "
              f"(at 0.49 fs: {a49:.1f} dB)")


def write_vh(out):
    lines = ["// Generated by sw/dsp_models/wb_fir.py vh -- do not edit.",
             f"// {NT}-tap symmetric wideband FIR profiles, DC gain 2^{COEF_FRAC}; profile 0 = bypass.",
             "function signed [17:0] wb_coef(input [1:0] prof, input [4:0] k);",
             "  begin",
             "    wb_coef = 18'sd0;",
             "    case ({prof, k})"]
    for p in (0, 1, 2, 3):
        for k, v in enumerate(coefs(p)):
            if v:
                s = f"-18'sd{-v}" if v < 0 else f"18'sd{v}"
                lines.append(f"      {{2'd{p}, 5'd{k}}}: wb_coef = {s};")
    lines += ["      default: wb_coef = 18'sd0;", "    endcase", "  end", "endfunction", ""]
    open(out, "w").write("\n".join(lines))


def round_half_even_shift(v, s):
    q, r = divmod(v, 1 << s)
    half = 1 << (s - 1)
    if r > half or (r == half and (q & 1)):
        q += 1
    return q


def fir_model(xs, c, width=24):
    """Bit-exact integer model of wb_fir: symmetric NT taps, round half to even, saturate."""
    taps = list(c) + list(c[-2::-1])
    lo, hi = -(1 << (width - 1)), (1 << (width - 1)) - 1
    hist = [0] * NT
    out = []
    for x in xs:
        hist = [x] + hist[:-1]
        acc = sum(t * h for t, h in zip(taps, hist))
        out.append(max(lo, min(hi, round_half_even_shift(acc, COEF_FRAC))))
    return out


def write_vectors(out, n=500, seed=5):
    """'C prof active' starts a case; then 'x y' hex pairs (24-bit two's complement).
    Each case is preceded by NT zero samples in the testbench (history flush)."""
    rng = np.random.default_rng(seed)
    m24 = (1 << 24) - 1
    lines = []
    for prof, active in ((1, 1), (2, 1), (3, 1), (0, 1), (1, 0)):
        lines.append(f"C {prof} {active}")
        xs = [int(v) for v in rng.integers(-(1 << 22), 1 << 22, n)]
        xs[100:110] = [(1 << 23) - 1] * 10          # full-scale steps: saturation
        xs[200:210] = [-(1 << 23)] * 10
        # profile 0 or not active: straight pass-through, no delay
        ys = fir_model(xs, coefs(prof)) if (active and prof) else list(xs)
        lines += [f"{x & m24:06x} {y & m24:06x}" for x, y in zip(xs, ys)]
    open(out, "w").write("\n".join(lines) + "\n")


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "study"
    if cmd == "study":
        study()
    elif cmd == "vh":
        write_vh(sys.argv[2])
    elif cmd == "vectors":
        write_vectors(sys.argv[2])
