// Generated by sw/dsp_models/wb_fir.py vh -- do not edit.
// 33-tap symmetric wideband FIR profiles, DC gain 2^16; profile 0 = bypass.
function signed [17:0] wb_coef(input [1:0] prof, input [4:0] k);
  begin
    wb_coef = 18'sd0;
    case ({prof, k})
      {2'd0, 5'd16}: wb_coef = 18'sd65536;
      {2'd1, 5'd0}: wb_coef = 18'sd470;
      {2'd1, 5'd1}: wb_coef = -18'sd390;
      {2'd1, 5'd2}: wb_coef = 18'sd477;
      {2'd1, 5'd3}: wb_coef = -18'sd507;
      {2'd1, 5'd4}: wb_coef = 18'sd446;
      {2'd1, 5'd5}: wb_coef = -18'sd263;
      {2'd1, 5'd6}: wb_coef = -18'sd64;
      {2'd1, 5'd7}: wb_coef = 18'sd545;
      {2'd1, 5'd8}: wb_coef = -18'sd1177;
      {2'd1, 5'd9}: wb_coef = 18'sd1935;
      {2'd1, 5'd10}: wb_coef = -18'sd2780;
      {2'd1, 5'd11}: wb_coef = 18'sd3657;
      {2'd1, 5'd12}: wb_coef = -18'sd4502;
      {2'd1, 5'd13}: wb_coef = 18'sd5249;
      {2'd1, 5'd14}: wb_coef = -18'sd5834;
      {2'd1, 5'd15}: wb_coef = 18'sd6207;
      {2'd1, 5'd16}: wb_coef = 18'sd58598;
      {2'd2, 5'd0}: wb_coef = -18'sd387;
      {2'd2, 5'd1}: wb_coef = 18'sd10;
      {2'd2, 5'd2}: wb_coef = 18'sd146;
      {2'd2, 5'd3}: wb_coef = -18'sd392;
      {2'd2, 5'd4}: wb_coef = 18'sd684;
      {2'd2, 5'd5}: wb_coef = -18'sd938;
      {2'd2, 5'd6}: wb_coef = 18'sd1054;
      {2'd2, 5'd7}: wb_coef = -18'sd922;
      {2'd2, 5'd8}: wb_coef = 18'sd451;
      {2'd2, 5'd9}: wb_coef = 18'sd405;
      {2'd2, 5'd10}: wb_coef = -18'sd1632;
      {2'd2, 5'd11}: wb_coef = 18'sd3146;
      {2'd2, 5'd12}: wb_coef = -18'sd4796;
      {2'd2, 5'd13}: wb_coef = 18'sd6388;
      {2'd2, 5'd14}: wb_coef = -18'sd7717;
      {2'd2, 5'd15}: wb_coef = 18'sd8598;
      {2'd2, 5'd16}: wb_coef = 18'sd57340;
      {2'd3, 5'd0}: wb_coef = 18'sd333;
      {2'd3, 5'd1}: wb_coef = -18'sd153;
      {2'd3, 5'd2}: wb_coef = -18'sd41;
      {2'd3, 5'd3}: wb_coef = 18'sd372;
      {2'd3, 5'd4}: wb_coef = -18'sd685;
      {2'd3, 5'd5}: wb_coef = 18'sd750;
      {2'd3, 5'd6}: wb_coef = -18'sd377;
      {2'd3, 5'd7}: wb_coef = -18'sd449;
      {2'd3, 5'd8}: wb_coef = 18'sd1472;
      {2'd3, 5'd9}: wb_coef = -18'sd2198;
      {2'd3, 5'd10}: wb_coef = 18'sd2037;
      {2'd3, 5'd11}: wb_coef = -18'sd561;
      {2'd3, 5'd12}: wb_coef = -18'sd2275;
      {2'd3, 5'd13}: wb_coef = 18'sd6017;
      {2'd3, 5'd14}: wb_coef = -18'sd9800;
      {2'd3, 5'd15}: wb_coef = 18'sd12615;
      {2'd3, 5'd16}: wb_coef = 18'sd51422;
      default: wb_coef = 18'sd0;
    endcase
  end
endfunction
